name: 'mydemo'
services:
  db:
    image: 'postgres'
    ports:
      - '2345:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'mydb'
  server:
    build: .
    ports:
      - '1060:1060'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/mydb?schema=public'
